/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author vidan
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("State machine.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButton1 = new form.PanelButton();
        panelState1 = new form.panelState();
        pnlCurrentState1 = new form.pnlCurrentState();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(panelButton1, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout panelState1Layout = new javax.swing.GroupLayout(panelState1);
        panelState1.setLayout(panelState1Layout);
        panelState1Layout.setHorizontalGroup(
            panelState1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        panelState1Layout.setVerticalGroup(
            panelState1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(panelState1, java.awt.BorderLayout.CENTER);
        getContentPane().add(pnlCurrentState1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private form.PanelButton panelButton1;
    private form.panelState panelState1;
    private form.pnlCurrentState pnlCurrentState1;
    // End of variables declaration//GEN-END:variables

    public form.pnlCurrentState getCurrentStatePanel(){
        return pnlCurrentState1;
    }
    public form.PanelButton getPanelButton(){
        return panelButton1;
    }
    public form.panelState getPanelState(){
        return panelState1;
    }
}
