/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.LinkedList;
import model.Paper;
import state.*;

/**
 *
 * @author vidan
 */
public class panelState extends javax.swing.JPanel {

    /**
     * Creates new form panelState
     */
    Paper paper;
    State currentState;
    LinkedList<State> states = new LinkedList<>();
    LinkedList<State> finalStates = new LinkedList<>();
    LinkedList<Component> komponente = new LinkedList<>();

    public panelState() {
        initComponents();
        paper = new Paper();
        currentState = paper.getCurrentState();
        states.add(WritingState.getInstance());
        states.add(ReviewState.getInstance());
        finalStates.add(CancelState.getInstance());
        finalStates.add(AcceptedState.getInstance());
        finalStates.add(RejectState.getInstance());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void paint(Graphics g) {

        int x = 120;
        int y = 20;
        for (State state : states) {
            Component comp = new Component(state, x, y, currentState);
            comp.initComponent(g);
            if (!komponente.contains(comp)) {
                komponente.add(comp);
            }
            x += 150;
        }
        g.drawLine(220, 70, 270, 70);
        g.drawLine(260, 62, 270, 70);
        g.drawLine(260, 78, 270, 70);
        
        g.drawLine(215, 50, 275, 50);
        g.drawLine(215, 50, 225, 58);
        g.drawLine(215, 50, 225, 42 );
        
        x = 50;
        y += 150;
        for (State state : finalStates) {
            Component comp = new Component(state, x, y, currentState);
            comp.initComponent(g);
            if (!komponente.contains(comp)) {
                komponente.add(comp);
            }
            x += 150;
        }
        g.drawLine(160, 120, 130, 180);
        g.drawLine(150, 170, 130, 180);
        g.drawLine(125, 160, 130, 180);
        
        g.drawLine(310, 120, 280, 180);
        g.drawLine(300, 170, 280, 180);
        g.drawLine(275, 160, 280, 180);
        
        
        
        g.drawLine(335, 120, 380, 175);
        g.drawLine(380, 150, 380, 175);
        g.drawLine(360, 170, 380, 175);

    }

    public State getState() {
        return paper.getCurrentState();
    }

    public void setCurrentState(State state) {
        currentState = state;
    }

}
